export const navOption=[
    {
        id:1,
        title:'Home',
        link:'/home',
        cName:'nav-links',
    },
    {
        id:2,
        title:'About',
        link:'/about',
        cName:'nav-links',
    },
    {
        id:3,
        title:'Contact',
        link:'/contact',
        cName:'nav-links',
    },
    {
        id:4,
        title:'Projects',
        link:'/projects',
        cName:'nav-links',
    },
]